source "https://rubygems.org"

gem "rake"
gem "ruboty-alias"
gem "ruboty-cron"
gem "ruboty-google_image"
gem "ruboty-redis"
gem "ruboty-slack"
gem "ruboty-talk"
gem "ruboty-hitozuma"
gem "ruboty-scorekeeper"
gem "ruboty-lgtm"
gem "ruboty-kokodeikku"
